name = "Dice"
uuid = "c81b9fed-521b-4ec1-87e0-ceb18a1eac4a"
authors = ["phyxmeow <XueHaotian@outlook.com>"]
version = "0.7.3"

[deps]
ConfigEnv = "01234589-554d-41b7-ae5c-7b6ee2db6796"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Telegram = "1da6f4ae-116c-4c38-8ee9-19974ff3601d"
